### ISSUE TITLE
[meta/main.yml] platforms supported is outdated

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#127]
Platforms supported lists trusty, which doesn't work anymore.
Moreover, some new platforms are added, platform tag needs to be updated as per travis jobs.

**Comment by Dhiraj240** [comment]
can i be assigned this issue ? also can you give example of new platforms which are added in it.

**Comment by atb00ker** [comment]
Yes, you can start working on this issue. :smile: 
Find about the platforms here: https://travis-ci.org/openwisp/ansible-openwisp2

**Comment by Dhiraj240** [comment]
as per travis under build system  trusty is present
```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
Also i could see only linux 
```
OS name: "linux", version: "4.4.0-98-generic", arch: "amd64", family: "unix"
```
Correct me if i have left something.

**Comment by atb00ker** [comment]
No, you are looking at the builder's information.
Here is the build matrix from `.travis.yml`:
```
env:
  matrix:
  - distro: centos:7
    playbook: test.yml
  - distro: 'ubuntu:16.04'
    playbook: test.yml
  - distro: 'ubuntu:18.04'
    playbook: test.yml
  - distro: debian:8
    playbook: test.yml
  - distro: debian:9
    playbook: test.yml
  - distro: debian:10
    playbook: test.yml
  - distro: fedora:27
    playbook: test.yml
  - distro: fedora:28
    playbook: test.yml
```
