### ISSUE TITLE
[controller] Add support for connections module (celery)

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#153]
We need to add support for the connections module and celery.

This implies requiring openwisp-controller 0.4.0 minimum.

**Comment by nemesisdesign** [comment]
Here's some information that should be useful to implement it.

Settings changes examples (can be re-adapted, I'm copypasting):

```python
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

if 'djcelery_email' not in INSTALLED_APPS:
    INSTALLED_APPS.append('djcelery_email')
    EMAIL_BACKEND = 'djcelery_email.backends.CeleryEmailBackend'
    CELERY_BROKER_URL = 'redis://127.0.0.1:6379/3'
```

Placing celery files:
```yaml
- name: supervisor celery
  template:
    src: templates/celery.j2
    dest: "{{ supervisor_path | format('celery') }}"
  notify: reload supervisor
  tags: [openwisp2, celery]
- copy:
    src: ./files/celery.py
    dest: "{{ openwisp2_path }}/openwisp2/celery.py"
    mode: 0664
    group: www-data
  notify: reload supervisor
  tags: [openwisp2, celery]
- copy:
    src: ./files/celery_init.py
    dest: "{{ openwisp2_path }}/openwisp2/__init__.py"
    mode: 0664
    group: www-data
  notify: reload supervisor
  tags: [openwisp2, celery]
```

templates/celery.j2

```ini
[program:celery]
user={{ www_user }}
directory={{ openwisp2_path }}
command={{ openwisp2_path }}/env/bin/celery -A openwisp2 worker -l info --pool=eventlet --concurrency=30 -Ofair
autostart=true
autorestart=true
stopsignal=INT
redirect_stderr=true
stdout_logfile={{ openwisp2_path }}/log/celery.log
stdout_logfile_maxbytes=30MB
stdout_logfile_backups=5
```

files/celery_init.py

```python
from __future__ import absolute_import, unicode_literals

from .celery import app as celery_app

__all__ = ['celery_app']
```

files/celery.py

```python
from __future__ import absolute_import, unicode_literals

import os

from celery import Celery
from django.conf import settings

from raven.contrib.celery import register_logger_signal, register_signal
from raven.contrib.django.raven_compat.models import client

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'openwisp2.settings')

app = Celery('openwisp2')
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks()
app.config_from_object('django.conf:settings', namespace='CELERY')

if hasattr(settings, 'RAVEN_CONFIG'):
    register_logger_signal(client)
    register_signal(client, ignore_expected=True)
```
