### ISSUE TITLE
[change] Improve Installation of custom modules

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#193]
For installing custom modules, the task `Install custom OpenWISP 2 Python packages` uses `--no-deps` options for [reasons mentioned in comment](https://github.com/openwisp/ansible-openwisp2/pull/188#discussion_r446474222) however, this causes [problems mentioned in the response](https://github.com/openwisp/ansible-openwisp2/pull/188#discussion_r448276422).

So, we should look ways to solve the original problem with ability to install dependencies! :smile:

**Comment by nemesisdesign** [comment]
I thought about a possible solution to this problem.

### Version vars

We could change the variables like `openwisp2_controller_version` to be full strings instead of partial strings.

Actual implementation:

```
# actual version string
openwisp2_firmware_upgrader_version: 0.1

# actual pip task:
pip:
    name: "openwisp-firmware-upgrader~={{ openwisp2_firmware_upgrader_version }}"
```

New implementation:

```
# new version string
openwisp2_firmware_upgrader_version: "openwisp-firmware-upgrader~=0.1"

# new pip task
pip:
    name: "openwisp-firmware-upgrader~={{ openwisp2_firmware_upgrader_version }}"
```

This will allow us to specify custom openwisp modules directly using the version var, making it obsolete to define the pip var.

### Get rid of "Install custom OpenWISP 2 Python packages" task

This task would be removed:

```
- name: Install custom OpenWISP 2 Python packages
  when: openwisp2_python_packages|length > 0
  pip:
    name: "{{ openwisp2_python_packages }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: true
    extra_args: "--no-deps"
  notify: reload supervisor
  retries: 5
  delay: 10
  register: result
  until: result is success
  tags:
    - molecule-idempotence-notest
```

### Handling of dependencies

Say a development version of openwisp-controller is being used, which also depends on a development version of openwisp-users.

The requirements of openwisp-controller should point this out as we recently did in [the requirements.txt of openwisp-radius](https://github.com/openwisp/openwisp-radius/blob/ee5220f/requirements.txt#L7-L9):

```
# Needed for the new authentication backend in openwisp-users
# TODO: remove when the new version of openwisp-users is released
openwisp-users @ https://github.com/openwisp/openwisp-users/tarball/<commit-id>
```

This syntax is available since pip 18 and is described in [PEP508](https://www.python.org/dev/peps/pep-0508/), I only found out recently, better late than never!

Then in the playbook file, both versions will have to be specified, eg:

```
openwisp2_controller_version: https://github.com/openwisp/openwisp-controller/tarball/<commit-id>
openwisp2_users_version: https://github.com/openwisp/openwisp-users/tarball/<commit-id>
```

### Conclusion

This should allow us to install custom OpenWISP modules and their dependencies without hacks.
It should also solve the idempotence issues (right now we first install the official modules and then install the custom ones, which is not idempotent).
