### ISSUE TITLE
nginx/openwisp binds to localhost and is not accessible from the device

### ISSUE THREAD

**Issue by bong1991** [openwisp/ansible-openwisp2#34]
Hey,

I set up my local PC and the device as described in the Readme in section "Install OpenWISP2 locally (laptop, desktop pc)".
However, binding the ansible via the playbook to the localhost makes it accessible from your own PC but does not expose the ansible instance to other devices.

I fixed this by making the following changes to the playbook:

```
- hosts: <IP-ADDRESS OF PC>
  roles: [openwisp.openwisp2]
  vars:
    postfix_myhostname: "<HOSTNAME>"
```

Maybe change the Readme accordingly?
