### ISSUE TITLE
CSRF issues

### ISSUE THREAD

**Issue by stefangweichinger** [openwisp/ansible-openwisp2#443]
I re-enabled an older VM with openwisp2 today and upgraded the setup using this role and newest ansible.

My playbook currently:

```
~/openwisp2-ansible-playbook/playbook.yml 
- hosts: openwisp2
  roles:
    - openwisp.openwisp2
  vars:
    openwisp2_default_from_email: "ow2@myother.tld"
    openwisp2_http_allowed_ip: "192.168.97.0/24"
    openwisp2_time_zone: "Europe/Berlin"
    openwisp2_django_cors:
      enabled: true
      allowed_origins_list: ["https://openwisp2.my.tld"]
```

This setup is proxied by HAproxy on a pfsense appliance, its IP 192.168.97.1 is in "openwisp2_http_allowed_ip", all this worked 2 years ago when I started this project.

The URL is "https://openwisp2.my.tld" and I have this in "allowed_origins_list"

Now I constantly get CSRF issues.

Tried "openwisp2_django_cors:
      enabled: false"

and various other things, I always get:

```
Forbidden (403)
CSRF verification failed. Request aborted.

Help
Reason given for failure:

    Origin checking failed - https://openwisp2.my.tld does not match any trusted origins.
```    

Same with another browser (Chrome and Firefox).

How to avoid that? Do I have to remove some parts of the old installation maybe and let the ansible role deploy it from scratch?

Thanks for any pointers!

EDIT:

additional info: I get the login mask, enter credentials, then the CSRF error is returned
