### ISSUE TITLE
[feature] Allow deploying WPA Enterprise 2 TTLS-PAP

### ISSUE THREAD

**Issue by nemesifier** [openwisp/ansible-openwisp2#462]
Let's find a way to allow users to deploy [WPA Enterprise 2 TTLS-PAP via OpenWISP RADIUS](https://openwisp-radius.readthedocs.io/en/stable/developer/freeradius_wpa_enterprise.html) more easily via this role.

I think we should generate the sites automatically given a list of organizations, each org supplying UUID, secret and a name (used just for internal purposes). However, I would leave the option to override the generation of a site if the user supplies a path to a template, so they can completely customize the site if needed.

Eg:

```
freeradius_eap_orgs:
  - name: org_a
    uuid: ...
    secret: ...
  - name: org_b
    uuid: ...
    secret: ...
    template: <path>
```
