### ISSUE TITLE
Add support for the upcoming Debian Stretch

### ISSUE THREAD

**Issue by zelda14** [openwisp/ansible-openwisp2#6]
While installing **ansible-openwisp2** on **Debian Stretch RC1** I face an *uwsgi* crash as ansible fetched uwsgi 2.0.14 from the PyPi repo. The crash is related to an *OpenSSL 1.1* incompatibility.

However while digging and experimenting, Debian successfully installed uwsgi from its own repo. 
In order to have a functionnal installation I modified the file : 

`/etc/ansible/roles/openwisp.openwisp2/tasks/pip.yml`

with the following informations :

```
- name: Install uwsgi
  pip:
    name: http://http.debian.net/debian/pool/main/u/uwsgi/uwsgi_2.0.14+20170111.orig.tar.gz
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - uwsgi
  notify: reload supervisor
```

That way pip fetch, build and doesn't complain.

Thanks

**Comment by nemesisdesign** [comment]
More info supplied on the [mailing list](https://groups.google.com/d/msg/openwisp/ggPqa9e1PVQ/MkBczcH8EAAJ):

I've updated my configuration and got some issues I solved, here is my feedback on the upcoming Debian stretch.

**1**: no issue while running:  ansible-galaxy install --force openwisp.openwisp2

**2**: Python 2 and Python 3 are installed on my system.

when running:

    ansible-playbook -i hosts playbook.yml -u xavier -k --ask-sudo-pass

I got a problem with:

    "No package matching 'python-software-properties' is available"

In my environment the package has been deprecated in favor of:

    sudo apt-get install python-software-properties
    Reading package lists... Done 
    Building dependency tree
    Reading state information... Done 
    Package python-software-properties is not available, but is referred to by another package. 
    This may mean that the package is missing, has been obsoleted, or 
    is only available from another source 
    However the following packages replace it: 
        software-properties-common

I updated the `apt.yml` accordingly and the problem is gone

**3**: - Then I face:

   ImportError: No module named 'pyparsing'

There is two ways to fix it.
Add the dependency in `apt.yml`:

```yaml
- name: Install python3 packages
  when: openwisp2_python == "python3"
  apt: name={{ item }} state=latest
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - python-virtualenv
    - python3-pyparsing
````

or through pip with:

    sudo pip3 install pyparsing
