### ISSUE TITLE
Issues with Stouts.postfix

### ISSUE THREAD

**Issue by UtkarshVerma** [openwisp/ansible-openwisp2#76]
The postfix role fails if the apt cache on production server isn't up to date. We can fix this by doing the APT cache update task before it.

**Comment by UtkarshVerma** [comment]
The fix is to add the following statements in the playbook to do the apt update before postfix role is executed:
```yml
  pre_tasks:
    - name: Update APT package cache
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
```
